### ISSUE TITLE
Add DumpUnitary function

### ISSUE THREAD

**Issue by tcNickolas** [microsoft/qsharp-runtime#179]
**Please describe what you would like the feature to accomplish.**
It would be extremely helpful to be able to see a matrix representation of a Q# operation.

**Describe the solution you'd like**
A `DumpUnitary` function that would take an operation on N qubits as a parameter and dump an array of complex numbers that is a matrix representation of that unitary. It could use Choi–Jamiłkowski isomorphism to extract those coefficients from the amplitudes of a state prepared in a specific way.

**Describe alternatives you've considered**
My current workaround is https://github.com/microsoft/QuantumKatas/tree/master/utilities/DumpUnitary, but it is fairly fragile (it broke when DumpMachine output format broke, it doesn't account for relative phases between columns, and so on). This really seems like something that should be part of the built-in language capabilities, not something that each user has to implement for themselves.

**Comment by cgranade** [comment]
As discussed offline earlier, I made a prototype for this. If you're interested in it, happy to share that prototype. I would suggest that the name of the Q# operation not expose simulator internals (i.e.: "unitary"), just as `DumpRegister` doesn't reference dumping a state since that's an internal simulator detail. From that perspective, I'd suggest putting `DumpOperation` forward for API review if you're interested in this feature again.

**Comment by cgranade** [comment]
Concretely, you can see the **rough** prototype at https://github.com/cgranade/QuantumLibraries/tree/cgranade/_experimental/dump-ops.

**Comment by cgranade** [comment]
@tcNickolas: There's a much less rough effort up at https://github.com/microsoft/QuantumLibraries/pull/302, if you'd be interested in taking a look to see if that meets your usecase. Thanks!

**Comment by tcNickolas** [comment]
I'm happy with DumpOperation implementation for this, so closing the issue. Thank you @cgranade for doing this!
