### ISSUE TITLE
Remove unnecessary const declarations across the native simulator codebase

### ISSUE THREAD

**Issue by AniketDalvi** [microsoft/qsharp-runtime#321]
As a part of _public class interface_ a const setter doesn't make much sense, whatever the implementation details of other methods might be. If clients outside of the class need to use the setter (for example, tests), make it non-const for them and inside `flush()` do the assignment directly, without going through the setter.

_Originally posted by @irinayat-MS in https://github.com/microsoft/qsharp-runtime/pull/291_

**Comment by AniketDalvi** [comment]
The current native simulator codebase has some const declarations which results in some non-ideal design patterns including const setters. This issue is to rethink the logical\representational constness model of the data structures in the full-state simulator codebase.

**Comment by bettinaheim** [comment]
@swernli @dbwz8 Does this still make sense after Dave's refactoring?

**Comment by swernli** [comment]
I'll double check the code and see. It's definitely possible this was already addressed as part of Dave's latest work.

**Comment by bettinaheim** [comment]
@swernli Did you have a chance to take a quick look?

**Comment by swernli** [comment]
I did, and I think we don't need to leave this open. The work that originally prompted this issue was the wave function reordering, which Dave's is looking at refactoring now, but is not yet covered by the current outstanding PR (#361). Either the refactor will appropriately remove the consts that aren't logically correct, or it will rework the way the underlying data structures are modified in order to no longer need the setters and the existing code can remain const. But the issue of const setters is only present in the feature/simulator-enhancement branch that has Aniket's changes and is not actually present in master.

**Comment by swernli** [comment]
Simulator enhancements have been merged via #361 and this can be closed as it is no longer an issue.
