### ISSUE TITLE
PowI function in Math Package throws exception for exponent of -1.

### ISSUE THREAD

**Issue by lwoodyiii** [microsoft/qsharp-runtime#392]
In Microsoft.Quantum.Math package, when you call the PowI function with the exponent of -1, it throws a System.ArgumentOutOfRangeException.

**To Reproduce**
1. Write Q# PowI(2,-1);

**Comment by lwoodyiii** [comment]
I'd like to try and fix this. Where in the code should I do this?

**Comment by samarsha** [comment]
The code that throws the exception is in src/Simulation/Core/Extensions.cs:

https://github.com/microsoft/qsharp-runtime/blob/29f8ea74652b1aea6e87367281ef132d9c1fda04/src/Simulation/Core/Extensions.cs#L41-L46

But could I ask what the expected behavior is - what should the return value be? Since any number to a negative exponent is fractional, it can't be represented in the `long` return type.

**Comment by bettinaheim** [comment]
@lwoodyiii
For exponention (power) of Int and BigInt, negative exponents result in undefined behavior, see the Q# specification [here](https://github.com/microsoft/qsharp-language/blob/main/Specifications/Language/3_Expressions/ArithmeticExpressions.md). 
To get a meaningful result for negative exponents, the returned value would need to be a double, and the double overload for power should be used.

**Comment by lwoodyiii** [comment]
Agree on numbers <-1, but 100^-1 is still 100 (int). Should be if (power < -1).... spec does not say this... but oh well :)

**Comment by cgranade** [comment]
> Agree on numbers <-1, but 100^-1 is still 100 (int). Should be if (power < -1).... spec does not say this... but oh well :)

I'm not sure I follow, @lwoodyiii? 100⁻¹ = 1 / 100 = 0.01, which isn't an integer.
