### ISSUE TITLE
Casing should be consistent for Q# in Qsharp vs QSharp

### ISSUE THREAD

**Issue by swernli** [microsoft/qsharp-runtime#449]
Right now we have some places where we spell out Q# as Qsharp and others where we use QSharp. Confusingly, sometimes it will be different in the folder name vs the file name, as in "src/Simulation/**Qsharp**Core/Microsoft.Quantum.**QSharp**.Core.csproj." If the casing is wrong in a project reference it will work fine on Windows because both the filesystem and MSBuild are case-insensitive, but fail on Linux due to file system case-sensitivity.

Since CSharp and FSharp are both consistent with using a capital S, we should probably align to that.

**Comment by bettinaheim** [comment]
@swernli
Currently, the only place that uses capital S are the M.Q.QSharp.Core package (and correspondingly the project file). I agree that it would be better to align with CSharp and FSharp. The majority of the work is to find a way to properly deprecate the Sdk properties and items groups - that would/will be somewhat painful. Additionally, this will need to be coordinated with telemetry, since some of the properties are used there.

**Comment by samarsha** [comment]
> The majority of the work is to find a way to properly deprecate the Sdk properties and items groups - that would/will be somewhat painful.

@bettinaheim If you're referring to the Quantum SDK, I don't think deprecation is necessary, since MSBuild properties are case-insensitive. See here: https://github.com/microsoft/qsharp-runtime/pull/447#discussion_r528038717

**Comment by bettinaheim** [comment]
> > The majority of the work is to find a way to properly deprecate the Sdk properties and items groups - that would/will be somewhat painful.
> 
> @bettinaheim If you're referring to the Quantum SDK, I don't think deprecation is necessary, since MSBuild properties are case-insensitive. See here: [#447 (comment)](https://github.com/microsoft/qsharp-runtime/pull/447#discussion_r528038717)

I didn't realize! That indeed makes it a whole lot better. In that case I believe we would only have to check in with telemetry, and update our Sdk and builds.
