### ISSUE TITLE
C# Code generation failure when using explicitly specified generic parameter that is user defined type.

### ISSUE THREAD

**Issue by vadym-kl** [microsoft/qsharp-runtime#47]
## Describe the bug
C# Code generation failure when using explicitly specified generic parameter that is user defined type.

## To Reproduce
```
namespace Buggy {
 function DefaultT<'T>() : 'T {
   mutable arr = new 'T[1];
   return arr[0];
 }
 operation DefaultComplex() : Microsoft.Quantum.Math.Complex {
   let res = DefaultT<Microsoft.Quantum.Math.Complex>();
   return res;
 } 
}
```

## Expected behavior
Code compiles successfully.

## Actual behavior
C# compiler fails with the following errors:
```
Bug.qs(10,20): error CS0029: Cannot implicitly convert type 
'Microsoft.Quantum.Simulation.Core.QVoid' to
'Microsoft.Quantum.Math.Complex' [...]
Bug.qs(10,20): error CS1662: Cannot convert lambda expression to intended delegate
type because some of the return types in the block are
not implicitly convertible to the delegate return type [...]
```

## System information
- OS: Windows

- .NET Core Version: 2.2

**Comment by anpaz-msft** [comment]
Long story. Looks like:

we don't know the resolved type for `DefaultT` during compilation (which is odd, since the Type is explicitly set) `-->` which is causing the code to fallback to the runtime generic implementation `-->` at runtime the code can't identify the Type from the arguments (there are no arguments) and so it defaults to object  `-->` `QArray` thinks object it's `QVoid` `-->` there is cast exception when a `QVoid[]` is returned instead of `Complex[]`.

I would start at the beginning: figuring out why the C# code gen thinks `DefaultT<Microsoft.Quantum.Math.Complex>` still has open Type parameters, and take it from there. Somehwere around the [SimulationCode.fs](https://github.com/microsoft/qsharp-runtime/blob/master/src/Simulation/CsharpGeneration/SimulationCode.fs).

**Comment by bettinaheim** [comment]
@vadym-kl This seems to be the same issue that was fixed with https://github.com/microsoft/qsharp-runtime/pull/88.
