### ISSUE TITLE
CMake build is not consistent.

### ISSUE THREAD

**Issue by kuzminrobin** [microsoft/qsharp-runtime#589]
Resolve #587 first. If the issue (described below) is still present, then resolve if needed (or remove the instructions about the CMake build).

In [README.md](https://github.com/microsoft/qsharp-runtime/blob/main/src/QirRuntime/README.md) the command `cmake --build .` needs to be executed several times in a row for the build to succeed. This makes an impression that some _later_ steps are attempted earlier than some _earlier_ steps (which sometimes happens during the multi-threaded build). Likely some dependencies are missing in the CMake files. Consider adding those such that the CMake build succeeds, regardless of whether it is a single-threaded build or a multi-threaded one.

**Comment by swernli** [comment]
There is one top level CMakeLists.txt at [src\QirRuntime\CMakeLists.txt](https://github.com/microsoft/qsharp-runtime/blob/c832ef32d1d30775593a34f5880d4ad98691be8b/src/QirRuntime/CMakeLists.txt). Calling cmake on that file will build all the rest. In fact, if the top level file is not used, some of the inner folders won't build properly, because they rely on variables and earlier build steps handled by the top level file.

Given that, I'd be in favor of removing the instructions for using CMake manually and encouraging everyone to use the build script, which matches what our pipelines use.

**Comment by kuzminrobin** [comment]
Looks like `--target install` was the missing part. Some more details are [here](https://github.com/microsoft/qsharp-runtime/pull/591#discussion_r602032856).
The steps are removed any way. So this issue is not applicable any more.
