### ISSUE TITLE
DrawRandomInt should work when min and max are equal

### ISSUE THREAD

**Issue by rhpreston** [microsoft/qsharp-runtime#602]
## Describe the bug
DrawRandomInt produces an ExecutionFailExecption when min and max parameters are equal.

## To Reproduce
Call Microsoft.Quantum.Random.DrawRandomInt with the same number for min and max. For example, `DrawRandomInt(0, 0)`.

## Expected behavior
Random integer functions typically allow a range of 1, for situations where the range may be variable. For example, I would expect to be able to select a random index of an array like this:

```
// assume "array" is of length > 0
let randomIndex = DrawRandomInt(0, Length(array) - 1);
```

## Actual behavior
The above code will fail if array is of length 1.

## System information
N/A

**Additional context**
To be clear, the current behavior is intended per the [documentation](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.random.drawrandomint#remarks). Really the purpose of this issue is to ask if there is a reason why DrawRandomInt was implemented this way, and if the team would consider changing it.

Thanks :smile:

**Comment by bettinaheim** [comment]
Thanks for filing the issue, @rhpreston. 
I don't see a reason why it would have to be this way. To support this, the implementation in both the C# runtime and in the QIR runtime will need to be adapted. @cgranade @kuzminrobin Do you see any issues with that?

**Comment by cgranade** [comment]
No objections here; that would also be very nice for use with `MaybeChooseElement`.

**Comment by bettinaheim** [comment]
Given that the QIR runtime actually does already seem to support it (see [here](https://github.com/microsoft/qsharp-runtime/blob/9c2b086584943bbcd5b9055ec1629f73166e63b2/src/Qir/Runtime/lib/QSharpFoundation/intrinsicsMath.cpp#L74)), it sounds reasonable to support it in general. @rhpreston Do you by any chance want to make a contribution with that? I believe all that is needed is to edit the C# implementation [here](https://github.com/microsoft/qsharp-runtime/blob/b389b24188824edf864ff67e83dc6cd4b4fd034c/src/Simulation/Simulators/QuantumSimulator/SimulatorBase.cs#L463).

**Comment by kuzminrobin** [comment]
I looked at the [code](https://github.com/microsoft/qsharp-runtime/blob/75b616f710ea6ac6836265a2781a3a4d52037959/src/Qir/Runtime/lib/QSharpFoundation/intrinsicsMath.cpp#L76) of QIR runtime and ran a few tests. The QIR implementation runs as requested - for equal min and max returns min (does not fail). As I understand, this bug (if observed at all) relates to C# Runtime only.

FYI:
In the docs for [DrawRandomInt()](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.random.drawrandomint), [DrawRandomDouble()](https://docs.microsoft.com/en-us/qsharp/api/qsharp/microsoft.quantum.random.drawrandomdouble) I see:
> Fails if `max <= min`

I expected:
> Fails if max < min

Otherwise the docs contradict to themselves (to the fragment "An integer in the inclusive range from min to max with uniform probability").
I added the [PR](https://github.com/microsoft/qsharp-runtime/pull/605) to fix that.
