### ISSUE TITLE
Consider refactoring `IType3Core`.

### ISSUE THREAD

**Issue by kuzminrobin** [microsoft/qsharp-runtime#896]
For [`IType3Core`](https://github.com/microsoft/qsharp-runtime/blob/72f7e963077c4cebea641ecc50b1ce4417048453/src/Simulation/TargetDefinitions/Interfaces/IType3Core.cs#L6) consider 
inheriting from [`IType1Core`](https://github.com/microsoft/qsharp-runtime/blob/72f7e963077c4cebea641ecc50b1ce4417048453/src/Simulation/TargetDefinitions/Interfaces/IType1Core.cs#L6) and [`IIntrinsicApplyUncontrolledSWAP`](https://github.com/microsoft/qsharp-runtime/blob/72f7e963077c4cebea641ecc50b1ce4417048453/src/Simulation/TargetDefinitions/Interfaces/IType3Core.cs#L15) 
rather than fully repeating the `IType1Core` (and adding the `IIntrinsicApplyUncontrolledSWAP`).

**Comment by bettinaheim** [comment]
Hm, I kind of liked that each target package has a full list of what it contains, and there is explicitly not intent that there should be any kind of hierarchy between the packages. Even though right now one interface is a strict subset, logically there is no relation between the two, and in the future they may diverge. 

@swernli What are your thoughts?

**Comment by swernli** [comment]
I agree with @bettinaheim for the reasons she listed. It seems a little redundant, but it also means every target package is independent and can be built up from smaller parts that can be mixed and matched. Since the target packages are meant to correspond to different backend capabilities, and there is no hierarchy or dependency between those backends, we'll be better served keeping the interfaces separate as well.

**Comment by kuzminrobin** [comment]
Understood. Makes sense, closing.
